# Generated by Django 4.2.29 on 2026-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auditlog_status_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('otp_attempt', 'OTP Attempt'), ('login_attempt', 'Login Attempt'), ('otp_verification', 'OTP Verification'), ('event_creation', 'Event Creation'), ('event_action', 'Event Action'), ('event_registration', 'Event Registration'), ('file_upload', 'File Upload'), ('attendance_mark', 'Attendance Marking'), ('event_deletion', 'Event Deletion')], max_length=50),
        ),
    ]
