# Generated by Django 4.2.29 on 2026-04-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_otp_remove_user_otp_expiry_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
