from django.urls import path
from .views import (
    RegisterView, 
    LoginView, 
    VerifyOTPView, 
    UserProfileView,
    ForgotPasswordView,
    ResetPasswordView,
    AdminCreateUserView,
    BulkHODUploadView,
    BulkTeacherUploadView,
    BulkStudentUploadView,
    HODListView,
    HODDetailView,
    TeacherListView,
    TeacherDetailView,
    StudentListView,
    StudentDetailView,
    BulkHODDeleteView,
    BulkTeacherDeleteView,
    BulkStudentDeleteView
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('admin-create-user/', AdminCreateUserView.as_view(), name='admin-create-user'),
    path('bulk-hod-upload/', BulkHODUploadView.as_view(), name='bulk-hod-upload'),
    path('bulk-teacher-upload/', BulkTeacherUploadView.as_view(), name='bulk-teacher-upload'),
    path('bulk-student-upload/', BulkStudentUploadView.as_view(), name='bulk-student-upload'),
    path('bulk-hod-delete/', BulkHODDeleteView.as_view(), name='bulk-hod-delete'),
    path('bulk-teacher-delete/', BulkTeacherDeleteView.as_view(), name='bulk-teacher-delete'),
    path('bulk-student-delete/', BulkStudentDeleteView.as_view(), name='bulk-student-delete'),
    path('hods/', HODListView.as_view(), name='hod-list'),
    path('hods/<int:id>/', HODDetailView.as_view(), name='hod-detail'),
    path('teachers/', TeacherListView.as_view(), name='teacher-list'),
    path('teachers/<int:id>/', TeacherDetailView.as_view(), name='teacher-detail'),
    path('students/', StudentListView.as_view(), name='student-list'),
    path('students/<int:id>/', StudentDetailView.as_view(), name='student-detail'),
]
