# Generated by Django 4.2.29 on 2026-04-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_event_approved_event_max_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='metadata',
        ),
        migrations.AddField(
            model_name='report',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='reports/docs/'),
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdf/'),
        ),
        migrations.AddField(
            model_name='report',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='participant_list',
            field=models.FileField(blank=True, null=True, upload_to='reports/docs/'),
        ),
        migrations.AddField(
            model_name='report',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='reports/photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='reports/photos/'),
        ),
        migrations.AddField(
            model_name='report',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='reports/posters/'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('hod_approved', 'HOD_APPROVED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=20),
        ),
    ]
