# Generated by Django 4.2.29 on 2026-04-11 19:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_remove_report_file_remove_report_generated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='photo2',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 11, 19, 20, 51, 314501, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('hod_approved', 'HOD APPROVED'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='reports/certificates/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.department'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/pdfs/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='objective',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='outcome',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='participant_list',
            field=models.FileField(blank=True, null=True, upload_to='reports/participants/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Post-Event', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
